[INFO] No checkpoint found at None. Starting from scratch.
Start_epoch: 0, start_step: 0
Starting epoch 1/100...
Evaluating:   4%|â–ˆ                            | 7/188 [00:31<13:35,  4.51s/it]
Global Max: 0.12886852025985718
Exception in thread Thread-5 (_pin_memory_loop):7/188 [00:30<05:12,  1.73s/it]
Traceback (most recent call last):
  File "/root/miniconda3/envs/rewas/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/rewas/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/rewas/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 59, in _pin_memory_loop
    do_one_step()
  File "/root/miniconda3/envs/rewas/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 35, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/root/miniconda3/envs/rewas/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/root/miniconda3/envs/rewas/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 541, in rebuild_storage_fd
    fd = df.detach()
  File "/root/miniconda3/envs/rewas/lib/python3.10/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/root/miniconda3/envs/rewas/lib/python3.10/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/root/miniconda3/envs/rewas/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/root/miniconda3/envs/rewas/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/workspace/rewas/./train_miil.py", line 339, in <module>
    main(args)
  File "/workspace/rewas/./train_miil.py", line 264, in main
    avg_loss1, avg_loss2, avg_loss3, avg_iou1, avg_iou2, avg_iou3 = evaluate(phi, video_encoder, test_loader, synchformer_cfg.training.use_half_precision)
  File "/workspace/rewas/evaluate_cam.py", line 46, in evaluate
    for step, batch in enumerate(tqdm(dataloader, desc="Evaluating", dynamic_ncols=False)):
  File "/root/miniconda3/envs/rewas/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/root/miniconda3/envs/rewas/lib/python3.10/site-packages/accelerate/data_loader.py", line 563, in __iter__
    next_batch = next(dataloader_iter)
  File "/root/miniconda3/envs/rewas/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/rewas/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1448, in _next_data
    idx, data = self._get_data()
  File "/root/miniconda3/envs/rewas/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1402, in _get_data
    success, data = self._try_get_data()
  File "/root/miniconda3/envs/rewas/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1243, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/root/miniconda3/envs/rewas/lib/python3.10/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/root/miniconda3/envs/rewas/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
